#!/bin/bash  
export CUDA_VISIBLE_DEVICES=0
# export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
# python -m torch.distributed.run --nproc_per_node=2 --rdzv_backend=c10d --rdzv_endpoint=localhost:0 train.py --genie_config genie/configs/magvit_n32_h8_d256.json --resume_from_checkpoint /home/aditya/1xgpt-The-North-Team/logs/train_cosmos-03-29-16-06/step_10000 --train_data_dir /home/aditya/1xgpt-The-North-Team_testing/data/train_v2.0 --val_data_dir /home/aditya/1xgpt-The-North-Team_testing/data/val_v2.0 --log_name train_cosmos --output_dir logs --max_eval_steps 1000  --seed 5 --eval_every_n_steps 8000 --per_device_train_batch_size 8 --per_device_eval_batch_size 8  --gradient_accumulation_steps 2 --max_train_steps 150000 --learning_rate 0.00003

python -m torch.distributed.run --nproc_per_node=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:0 train.py --genie_config genie/configs/cosmos.json --train_data_dir /home/aditya/1xgpt-The-North-Team_testing/data/train_v2.0 --val_data_dir /home/aditya/1xgpt-The-North-Team_testing/data/val_v2.0 --log_name train_cosmos_one_vocab --output_dir logs --max_eval_steps 1000  --seed 5 --eval_every_n_steps 8000 --per_device_train_batch_size 4 --per_device_eval_batch_size 4  --gradient_accumulation_steps 2 --max_train_steps 150000 --learning_rate 0.00003
# python -m torch.distributed.run --nproc_per_node=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:0 train.py --resume_from_checkpoint /home/aditya/1xgpt-The-North-Team/logs/train_cosmos_one_vocab-04-04-19-18/step_60000 --genie_config genie/configs/cosmos.json --train_data_dir /home/aditya/1xgpt-The-North-Team_testing/data/train_v2.0 --val_data_dir /home/aditya/1xgpt-The-North-Team_testing/data/val_v2.0 --log_name train_cosmos_one_vocab --output_dir logs --max_eval_steps 1000  --seed 5 --eval_every_n_steps 8000 --per_device_train_batch_size 4 --per_device_eval_batch_size 4  --gradient_accumulation_steps 2 --max_train_steps 50000 --learning_rate 0.00001

# python train.py --genie_config genie/configs/magvit_n32_h8_d256_v0.json --train_data_dir ../data/train_v1.1 --val_data_dir ../data/val_v1.1 --log_name train_0 --output_dir logs --max_eval_steps 10 --seed 0 --resume_from_checkpoint /pub0/qasim/1xgpt/1xgpt/checkpoints/GENIE_35M
